name: Publish Docker image

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u DOCKER_USERNAME -p DOCKER_PASSWORD
    - name: Build the Docker image version
      run: docker build . --file docker/Dockerfile --tag tomyaacov/bppy-docker:${{ github.event.release.tag_name }}
    - name: Build the Docker image latest
      run: docker build . --file docker/Dockerfile --tag tomyaacov/bppy-docker:latest

    - name: Docker Push
      run: docker push tomyaacov/bppy-docker